development:
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

  facebook_client_id: <%= ENV["FACEBOOK_KEY"] %>
  facebook_client_secret: <%= ENV["FACEBOOK_SECRET"] %>